AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 t2.micro instance running Ubuntu 24.04 LTS in us-east-1 and associate an existing Elastic IP

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e2c8caa4b6378d8c
      KeyName: zabbix1
      SecurityGroupIds:
        - sg-01b79acc0eafe9d24
      SubnetId: subnet-0ee8a1e533bf483cc
      Tags:
        - Key: Name
          Value: MyUbuntuInstance

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MyEC2Instance
      EIP: eipalloc-087b95a143835a1a4

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref MyEC2Instance
