AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 t2.micro instance running Ubuntu 24.04 LTS in eu-west-2a and associate an existing Elastic IP

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05c172c7f0d3aed00
      KeyName: zabbix1
      SecurityGroupIds:
        - sg-0d398eec1c6b95a6e
      SubnetId: subnet-0d32b4be618fe4343
      Tags:
        - Key: Name
          Value: WP-blue

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MyEC2Instance
      AllocationId: eipalloc-0c8847552fb41b281

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref MyEC2Instance
