name: Blue/Green Env Deploy CloudFormation Stack 
on:
  push:
    branches:
      - main  
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deployed_env: ${{ env.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine deployment environment
        id: check-env
        run: |
          BLUE_INSTANCE=$(aws ec2 describe-addresses --allocation-ids eipalloc-0c8847552fb41b281 --query 'Addresses[0].InstanceId' --output text)
          
          if [ "$BLUE_INSTANCE" != "None" ]; then
            echo "Blue environment is active, switching to Green"
            echo "eip_id=eipalloc-086b8564c5978e818" >> $GITHUB_ENV
            echo "env_name=GREEN" >> $GITHUB_ENV
            echo "environment=GREEN" >> $GITHUB_OUTPUT
          else
            echo "Using Blue environment"
            echo "eip_id=eipalloc-0c8847552fb41b281" >> $GITHUB_ENV
            echo "env_name=BLUE" >> $GITHUB_ENV
            echo "environment=BLUE" >> $GITHUB_OUTPUT
          fi

      # Rest of your steps...

  trigger_blue:
    needs: deploy
    if: success() && needs.deploy.outputs.deployed_env == 'BLUE'
    uses: ./.github/workflows/blue-main.yml

  trigger_green:
    needs: deploy
    if: success() && needs.deploy.outputs.deployed_env == 'GREEN'
    uses: ./.github/workflows/green-main.yml
