name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to get the CloudFormation template
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials using the stored secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install AWS CLI (if not already installed in your GitHub runner)
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Deploy CloudFormation stack with dynamic stack name
      - name: Deploy CloudFormation stack
        run: |
          STACK_NAME="WP-BlUE-${{ github.run_id }}" 
          aws cloudformation deploy \
            --template-file CloudFormation.yml \  
            --stack-name $STACK_NAME            
