name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to get the CloudFormation template
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials using the stored secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy CloudFormation stack with dynamic stack name
      - name: Deploy CloudFormation stack
        run: |
          STACK_NAME="WP-BlUE-$(date +'%Y%m%d-%H%M%S')"

          # Debugging: Print out the value of STACK_NAME to verify it's correct
          echo "STACK_NAME is: $STACK_NAME"
          
          # Check if STACK_NAME is empty
          if [ -z "$STACK_NAME" ]; then
            echo "Error: STACK_NAME is empty!"
            exit 1
          fi

          # Ensure the CloudFormation template file exists
          if [ ! -f CloudFormation.yml ]; then
            echo "Error: CloudFormation.yaml not found!"
            exit 1
          fi

          # Run the CloudFormation deploy command
          aws cloudformation deploy --template-file CloudFormation.yaml --stack-name "$STACK_NAME"

