name: Terminate EC2 Instance

on:
 workflow_dispatch: # Manual trigger

jobs:
 terminate:
   runs-on: ubuntu-latest
   steps:
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
         
     - name: Terminate instance
       run: |
         echo "Finding instance associated with EIP eipalloc-092e331c98b8b9bfa..."
         
         # Get instance ID associated with the EIP
         INSTANCE_ID=$(aws ec2 describe-addresses \
           --allocation-ids eipalloc-092e331c98b8b9bfa \
           --query 'Addresses[0].InstanceId' \
           --output text)
         
         if [ "$INSTANCE_ID" != "None" ]; then
           echo "Found instance $INSTANCE_ID, terminating..."
           aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
           
           echo "Waiting for instance termination..."
           aws ec2 wait instance-terminated --instance-ids "$INSTANCE_ID"
           echo "Instance terminated successfully"
         else
           echo "No instance found associated with this EIP"
         fi
         
         # Disassociate EIP if needed
         ASSOCIATION_ID=$(aws ec2 describe-addresses \
           --allocation-ids eipalloc-092e331c98b8b9bfa \
           --query 'Addresses[0].AssociationId' \
           --output text)
           
         if [ "$ASSOCIATION_ID" != "None" ]; then
           echo "Disassociating Elastic IP..."
           aws ec2 disassociate-address --association-id "$ASSOCIATION_ID"
           echo "EIP disassociated successfully"
         else
           echo "EIP is not associated with any instance"
         fi
